# Generated by Django 5.0.1 on 2024-08-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="img"),
        ),
    ]
