# Generated by Django 5.0.1 on 2024-08-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0004_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.IntegerField(default=2, max_length=11),
            preserve_default=False,
        ),
    ]
