# Generated by Django 5.0.1 on 2024-08-02 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0005_profile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
    ]
