# Generated by Django 5.0.1 on 2024-08-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0011_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
