# Generated by Django 5.0.1 on 2024-08-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0015_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
