# Generated by Django 5.1 on 2024-08-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
